CREATE DATABASE idp;
CREATE USER idp WITH PASSWORD 'idp123';
GRANT CONNECT ON DATABASE idp TO idp;

\c idp;

CREATE EXTENSION pgcrypto;

CREATE TABLE IF NOT EXISTS credentials(
	employee_id TEXT NOT NULL,
	password_hash TEXT NOT NULL,
	created_at TIMESTAMPTZ NOT NULL,
	updated_at TIMESTAMPTZ NOT NULL,
	deleted_at TIMESTAMPTZ DEFAULT NULL,
	CONSTRAINT PK_CREDENTIALS PRIMARY KEY(employee_id)
);
GRANT SELECT, UPDATE, INSERT, DELETE ON credentials TO idp;

CREATE TABLE IF NOT EXISTS profiles(
	ehid TEXT NOT NULL,
	name TEXT NOT NULL,
	dob DATE NOT NULL,
	created_at TIMESTAMPTZ NOT NULL,
	updated_at TIMESTAMPTZ NOT NULL,
	CONSTRAINT PK_PROFILES PRIMARY KEY(ehid)
);
GRANT SELECT, UPDATE, INSERT, DELETE ON profiles TO idp;

CREATE TABLE IF NOT EXISTS tenures(
	id SERIAL,
	ehid TEXT NOT NULL,
	employee_id TEXT NOT NULL,
	start_date DATE NOT NULL,
	end_date DATE DEFAULT NULL,
	employment_type TEXT,
	created_at TIMESTAMPTZ NOT NULL,
	updated_at TIMESTAMPTZ NOT NULL,
	CONSTRAINT UK_WORK_PROFILES UNIQUE(ehid, start_date),
	CONSTRAINT PK_WORK_PROFILES PRIMARY KEY(id)
);
GRANT SELECT, UPDATE, INSERT, DELETE ON tenures TO idp;
GRANT USAGE ON SEQUENCE tenures_id_seq TO idp;

CREATE TABLE IF NOT EXISTS ktps(
	id TEXT NOT NULL,
	ehid TEXT NOT NULL,
	CONSTRAINT PK_KTPS PRIMARY KEY(id)
);
GRANT SELECT, UPDATE, INSERT, DELETE ON ktps TO idp;