app:
  datasource:
    host: 127.0.0.1
    port: 5432
    user: iam
    password: 123
    dbname: iam
    sslmode: disable
    timezone: Asia/Jakarta
  security:
    jwt:
      secret: 1nt3rst3ll4r-*-a5tR0
      valid-minute: 90
    